#!/usr/local/bin/fish

set state (amixer -c1 get Master | grep off > /dev/null; and echo off; or echo on)
if [ $state = 'off' ]
    set newstate on
else
    set newstate off
end

switch $argv[1]
case '+'
	amixer -c 1 sset Master 2dB+
	amixer -c 1 sset Headphone 2dB+ $state
	amixer -c 1 sset Speaker 2dB+ $state
	amixer -c 1 sset PCM 2dB+
case '-' ]
	amixer -c 1 sset Master 2dB-
	amixer -c 1 sset Headphone 2dB- $state
	amixer -c 1 sset Speaker 2dB- $state
	amixer -c 1 sset PCM 2dB-
case 'm' ]
	amixer -c 1 sset Master $newstate
	amixer -c 1 sset Headphone $newstate
	amixer -c 1 sset Speaker $newstate
	amixer -c 1 sset PCM
end
