#!/usr/local/bin/fish

if begin; test (count $argv) -gt 0; and test $argv[1] = "menu"; end
	echo -n $CLIPBOARD | sed '2,$ s|^\s||' | dmenu.xft -l 45 -nb "#000000" -nf "#0075FF" -sb "#00FF75" -sf "#000000"  -fn "DejaVu Sans Mono for Powerline:Bold:size=12" -p "clip" | tr -d '\n' | sed 's|↵|\n|g' | xsel -i
else
    set -U CLIPBOARD
	while true
		set -l RECENT (xsel -o | sed ':a;N;$!ba;s|\n|↵|g')
		if begin; test (count $RECENT) -gt 0; and contains $RECENT\n $CLIPBOARD; end
            set -e CLIPBOARD[(contains -i $RECENT\n $CLIPBOARD)]
        end
        set CLIPBOARD $RECENT\n $CLIPBOARD
		sleep 1
	end
end
